# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PapagoTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "Apollo"
  pod "Apollo/WebSocket"
  pod "SwiftLint"
  pod "ReactorKit"
  pod "RxCocoa"
  pod "Kingfisher"
  pod "RxGesture"
  pod "RxDataSources"
  pod "Toaster", :git => 'https://github.com/devxoul/Toaster', :branch => 'master'
  # Pods for PapagoTalk

  target 'ReactorTests' do
    inherit! :search_paths
    pod "ReactorKit"
    # Pods for testing
  end

  target 'MessageModelTests' do
    inherit! :search_paths
    pod "Apollo"
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
